### PR TITLE
[History Server] Tune CPU, memory, and event logging for cold loads

### PR DESCRIPTION
**Pull request by Future-Outlier**
## Why

Cold-loading large sessions is CPU- and memory-intensive. A `500m` CPU limit throttles loads, while one `Info` log per event adds avoidable work and noise.

- **CPU:** keep the `500m` request and leave the limit to operators. One 50k-task session, five randomized reads per setting: median **84s → 34s**.

  ```mermaid
  xychart-beta
      title "Cold load — before vs after"
      x-axis ["Before: 500m limit", "After: no limit"]
      y-axis "Cold-load time (seconds)" 0 --> 100
      bar [84, 34]
  ```

- **Per-event logging:** move `Info` to `Debug`. Separate 50k-task runs measured **97.9s → 85.3s** (~13%); these runs were not paired, so this is supporting evidence rather than an isolated causal estimate.

  ```mermaid
  xychart-beta
      title "Per-event logging — observed cold-load time"
      x-axis ["Before: Info", "After: Debug"]
      y-axis "Cold-load time (seconds)" 0 --> 110
      bar [97.9, 85.3]
  ```

- **Memory:** use a `2Gi` request, an `8Gi` encoded-cache soft bound, and a `12Gi` limit in all standalone examples. This leaves room for roughly one 100k-task decode; larger concurrent reads still need workload-specific tuning.

image

image

[Raw measurements and reproduction scripts](https://github.com/Future-Outlier/historyserver-benchmark).

## Checks

- [x] History Server build and race tests
- [x] E2E package compile
- [x] Manual Kind benchmarks

### CODE REVIEW

**Comment by Future-Outlier** [comment]
The two red checks are pre-existing on master, not from this PR.

`ray-operator/controllers/ray/rayservice_controller_unit_test.go:2637` calls `record.NewFakeRecorder(10)`, but the file's import block only has `k8s.io/client-go/tools/events` — every other recorder in that file is `events.*`. So `go vet ./ray-operator/...` fails at master (72b97677) with `undefined: record`, which is what both "Build Operator Binaries" and "Lint (pre-commit)" are reporting. It looks like a semantic merge conflict between two PRs that each passed on their own.

This PR only touches `historyserver/`, and "Build historyserver" passes.

File: historyserver/config/historyserver.yaml [hunk 1]
```diff
@@ -64,5 +64,10 @@ spec:
...
         - containerPort: 8080
         resources:
-          limits:
+          requests:
             cpu: "500m"
+          limits:
+            # Loading a dead session is CPU-bound: it uses ~1.2 cores with bursts
+            # to ~2.2. A 500m cap is saturated for the whole load, which made a
+            # 100k-task session take 907s instead of 63s.
+            cpu: "4"
```
Comment (win5923) [inline historyserver/config/historyserver.yaml]:
```suggestion
          requests:
            cpu: "500m"
```


Just wondering if we should only set the CPU requests by default to disable CFS quota, and let users configure CPU limits themselves if they want them.

https://x.com/thockin/status/1134193838841401345

**Review by win5923 — APPROVED** [review]

File: historyserver/config/historyserver.yaml (hunk 1 above)
Comment (Future-Outlier) [reply historyserver/config/historyserver.yaml]: Updated in e4a26d1ae to keep requests.cpu at 500m and omit the sample-level CPU limit. The Kind results show why: a 500m hard limit took 151.3s for 100k tasks, versus 67.9s with a 4-core limit; request-only/no-limit trials took 74.4s and 81.7s, with sampled peaks around 2 cores. The 4-core ceiling never bound, so it is an isolation policy rather than a performance requirement. Users or a namespace LimitRange can add the appropriate limit. I also updated the PR description so it does not claim that no limit is faster than 4 cores.

File: historyserver/config/historyserver.yaml [hunk 2]
```diff
@@ -64,5 +64,5 @@ spec:
         ports:
         - containerPort: 8080
         resources:
-          limits:
+          requests:
```
Comment (andrewsykim) [inline historyserver/config/historyserver.yaml:73]: While we're at it, I wonder if we should have memory request and limits here? The memory limit should be tuned to the caching that @JiangJiaWei1103 added

Comment (andrewsykim) [reply historyserver/config/historyserver.yaml:73]: Based on https://github.com/ray-project/kuberay/pull/4960#discussion_r3736572168, we're defaulting max bytes to 2GiB. 

Maybe in the example overwrite max bytes to 8GiB and set limit to 8GiB (or a little more for headroom)

Comment (Future-Outlier) [reply historyserver/config/historyserver.yaml:73]: no problem

Comment (Future-Outlier) [reply historyserver/config/historyserver.yaml:73]: image

Comment (Future-Outlier) [reply historyserver/config/historyserver.yaml:73]: ~~Added a 2Gi memory request and 4Gi limit in 7b4833e5c, while keeping the default 2Gi cache.~~

Comment (Future-Outlier) [reply historyserver/config/historyserver.yaml:73]: Updated in 0e1b497d. The three standalone examples now use a 2Gi request, an 8Gi encoded-cache soft bound, and a 12Gi limit. An 8Gi limit would leave no room for request-time decoding; 12Gi covers roughly one 100k-task GET, while larger concurrent reads still need workload-specific tuning.

Comment (Future-Outlier) [reply historyserver/config/historyserver.yaml:73]: update experiment:
image

**Review by KunWuLuan — APPROVED** [review]

File: historyserver/config/historyserver-azureblob.yaml [hunk 3]
```diff
@@ -46,6 +46,13 @@ spec:
         - --ray-root-dir=log
         ports:
         - containerPort: 8080
+        # Cache is soft-bounded at 8 GiB; 12 GiB leaves decode headroom.
+        # The 2 GiB request keeps examples schedulable; size production requests to residency.
+        args:
+        - --session-cache-max-bytes=8589934592
```
Comment (andrewsykim) [inline historyserver/config/historyserver-azureblob.yaml:52]: @JiangJiaWei1103 can we consider renaming this flag to `--session-cache-max-memory` and have it accept a string like `8GiB`?

**Review by andrewsykim — APPROVED** [review]

File: historyserver/config/historyserver-azureblob.yaml (hunk 3 above)
Comment (Future-Outlier) [reply historyserver/config/historyserver-azureblob.yaml:52]: cc @machichima @win5923 to take over if jia-wei doesn't have bandwidth.

Comment (win5923) [reply historyserver/config/historyserver-azureblob.yaml:52]: opened a PR here:
https://github.com/ray-project/kuberay/pull/5139
