### PR TITLE
Fix helm default

### PR DESCRIPTION
**Pull request by bplotnick-humane**
## Why are these changes needed?

Introduced in https://github.com/ray-project/kuberay/pull/451. Without a default value, helm throws:

```
... error calling ne: incompatible types for comparison
```

## Checks

- [ ] I've made sure the tests are passing. 
- Testing Strategy
   - [ ] Unit tests
   - [x] Manual tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by DmitriGekhtman** [comment]
> You can repro this with: `helm template .` from within the `kuberay/helm-chart/ray-cluster` directory

Which commit are using locally (`git rev-parse HEAD`)?
I do not get an error with current master.

**Comment by kevin85421** [comment]
This issue will only happen in old helm versions. See #548 for more details. This issue and #537 #543 are duplicate. Thank @bplotnick-humane for pointing this out!
