### PR TITLE
[RayService] Fix broken build: use events.NewFakeRecorder in unit test

### PR DESCRIPTION
**Pull request by KunWuLuan**
## Why

`master` currently does not compile. `golangci-lint` (pre-commit) fails on every open PR with:

```
ray-operator/controllers/ray/rayservice_controller_unit_test.go:2637:13: undefined: record (typecheck)
```

## Root cause

A semantic merge conflict between two independently-green PRs:

- The file was migrated from `k8s.io/client-go/tools/record` to `k8s.io/client-go/tools/events`; every recorder in it now uses `events.NewFakeRecorder(...)` / `events.FakeRecorder{}`, and `tools/record` is no longer imported.
- #4894 (commit a6f00357) added a lone `record.NewFakeRecorder(10)` at line 2637, written against a base that still imported `tools/record`.

Merged together, `record` is undefined, so the test package fails to typecheck. Each PR passed CI on its own base; the combination on `master` does not compile.

## Fix

Switch the single stray call to `events.NewFakeRecorder(10)`, matching every other recorder in the file (e.g. lines 476, 909). One line, no import changes.

## Verification

```
cd ray-operator && go vet ./controllers/ray/   # passes (previously: undefined: record)
```

### CODE REVIEW

**Comment by machichima** [comment]
I think this is duplicated with https://github.com/ray-project/kuberay/pull/5084

**Comment by KunWuLuan** [comment]
Closing this PR as it is duplicated by #5084 (already merged by Future-Outlier on 2026-08-06).
